//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leosac.WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leosac.WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the latest version..
        /// </summary>
        public static string AlreadyLastUpdate {
            get {
                return ResourceManager.GetString("AlreadyLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic updates.
        /// </summary>
        public static string AutomaticUpdates {
            get {
                return ResourceManager.GetString("AutomaticUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update now.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source code of this software is released under the GNU GPL v3 license..
        /// </summary>
        public static string CodeLicense {
            get {
                return ResourceManager.GetString("CodeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the new version now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Support.
        /// </summary>
        public static string EmailSupport {
            get {
                return ResourceManager.GetString("EmailSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet connection is required, that&apos;s all!.
        /// </summary>
        public static string InternetRequired {
            get {
                return ResourceManager.GetString("InternetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active plan..
        /// </summary>
        public static string InvalidPlan {
            get {
                return ResourceManager.GetString("InvalidPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries / Credits.
        /// </summary>
        public static string LibrariesCredits {
            get {
                return ResourceManager.GetString("LibrariesCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string LicenseKey {
            get {
                return ResourceManager.GetString("LicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plan/license key.
        /// </summary>
        public static string LicenseKeyHelper {
            get {
                return ResourceManager.GetString("LicenseKeyHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Console.
        /// </summary>
        public static string LogConsole {
            get {
                return ResourceManager.GetString("LogConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Plan.
        /// </summary>
        public static string MaintenancePlan {
            get {
                return ResourceManager.GetString("MaintenancePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Plan.
        /// </summary>
        public static string MaintenancePlan1 {
            get {
                return ResourceManager.GetString("MaintenancePlan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active plan has been registered with this installation..
        /// </summary>
        public static string MaintenancePlanAdvert1 {
            get {
                return ResourceManager.GetString("MaintenancePlanAdvert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now to benefit from all the plan related services and to secure your business..
        /// </summary>
        public static string MaintenancePlanAdvert2 {
            get {
                return ResourceManager.GetString("MaintenancePlanAdvert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max lines:.
        /// </summary>
        public static string MaxLines {
            get {
                return ResourceManager.GetString("MaxLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New software update available!.
        /// </summary>
        public static string NewUpdateAvailable {
            get {
                return ResourceManager.GetString("NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open website.
        /// </summary>
        public static string OpenWebsite {
            get {
                return ResourceManager.GetString("OpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plan expires at.
        /// </summary>
        public static string PlanExpiration {
            get {
                return ResourceManager.GetString("PlanExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registered email address (optional).
        /// </summary>
        public static string RegisterEmailHelper {
            get {
                return ResourceManager.GetString("RegisterEmailHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an existing plan.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new plan and benefit from it.
        /// </summary>
        public static string RegisterPlan {
            get {
                return ResourceManager.GetString("RegisterPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Version.
        /// </summary>
        public static string SoftwareVersion {
            get {
                return ResourceManager.GetString("SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souscrire.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID.
        /// </summary>
        public static string UUID {
            get {
                return ResourceManager.GetString("UUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Installation Identifier.
        /// </summary>
        public static string UUIDHelper {
            get {
                return ResourceManager.GetString("UUIDHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a valid plan..
        /// </summary>
        public static string ValidPlan {
            get {
                return ResourceManager.GetString("ValidPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web browser.
        /// </summary>
        public static string WebBrowser {
            get {
                return ResourceManager.GetString("WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
